version: "3.8"
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      TZ: Europe/Istanbul
    volumes:
      - ./data:/app/data
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: filesharedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      TZ: Europe/Istanbul
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
